name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict
        && composer validate --strict --working-dir=devtools/php-cs-fixer
        && composer validate --strict --working-dir=devtools/phpstan
        && composer validate --strict --working-dir=devtools/phpunit

    - name: Cache Composer Packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Install Tools
      run: make
        devtools/php-cs-fixer/vendor/bin/php-cs-fixer
        devtools/phpstan/vendor/bin/phpstan
        devtools/phpunit/vendor/bin/phpunit

    - name: Run CodeStyle Check
      run: make codestyle

    - name: Run Static Analysis
      run: make stan

    - name: Run Test Suite
      run: make tests
